use std::sync::Arc;

use crate::types::room::Room;
use async_graphql::{Context, InputObject, SimpleObject};
use chrono::{DateTime, Utc};
use domain::message::Message as DomainMessage;
use service::ServiceContainer;
use thiserror::Error;
use uuid::Uuid;

/// GraphQL output type for a message.
#[derive(SimpleObject, Clone)]
pub struct Message {
    /// Id of the message, generated by the server on creation. Not to be confused with the idempotency key provided by the client in SendMessageInput.
    pub id: Uuid,
    pub created_at: DateTime<Utc>,
    pub content: String,
    /// Public ID of the sender.
    pub sender: Uuid,
    /// Public ID of the room.
    pub room: Uuid,
}

//TODO need to review if this is needed
impl From<DomainMessage> for Message {
    fn from(m: DomainMessage) -> Self {
        Self {
            id: m.id,
            created_at: m.created_at,
            content: m.content,
            sender: m.sender,
            room: m.room,
        }
    }
}

impl Message {
    /// True power of GraphQL: resolve the room details on demand when requested by the client.
    pub async fn room_details(&self, ctx: &Context<'_>) -> Result<Room, MessageError> {
        let services = ctx.data_unchecked::<Arc<ServiceContainer>>();
        let room = services
            .room
            .get_room_by_id(self.room)
            .await
            .map_err(|e| MessageError::RoomNotFound(self.room))?;
        Ok(Room::from(room))
    }
}

/// GraphQL input for sending a message.
#[derive(InputObject)]
pub struct SendMessageInput {
    pub content: String,
    /// Public ID of the sender.
    pub sender: Uuid,
    /// Public ID of the room.
    pub room: Uuid,
    /// Client-generated idempotency key to prevent duplicate sends on retries.
    pub idempotency_key: Uuid,
}

#[derive(Error, Debug)]
pub enum MessageError {
    #[error("Room not found on specified message {0}")]
    RoomNotFound(Uuid),
}
