use std::sync::Arc;

use async_graphql::{ComplexObject, Context, InputObject, SimpleObject, Union};
use chrono::{DateTime, Utc};
use domain::message::Message as DomainMessage;
use service::ServiceContainer;
use uuid::Uuid;

use super::error::RoomError;
use super::room::Room;

/// GraphQL output type for a message.
#[derive(Clone, SimpleObject)]
#[graphql(complex)]
pub struct Message {
    /// Id of the message, generated by the server on creation. Not to be confused with the idempotency key provided by the client in SendMessageInput.
    pub id: Uuid,
    pub created_at: DateTime<Utc>,
    pub content: String,
    /// Public ID of the sender.
    pub sender: Uuid,
    /// Public ID of the room (kept for resolution).
    #[graphql(skip)]
    pub room_id: Uuid,
}

/// Result union for the `room` complex field.
#[derive(Union)]
pub enum MessageRoomResult {
    Room(Room),
    #[graphql(flatten)]
    Error(RoomError),
}

/// Custom fields
#[ComplexObject]
impl Message {
    /// Resolves the room as a full object instead of just a UUID.
    async fn room(&self, ctx: &Context<'_>) -> MessageRoomResult {
        let services = ctx.data_unchecked::<Arc<ServiceContainer>>();
        match services.room.get_room_by_id(self.room_id).await {
            Ok(room) => MessageRoomResult::Room(room.into()),
            Err(e) => MessageRoomResult::Error(e.into()),
        }
    }
}

impl From<DomainMessage> for Message {
    fn from(m: DomainMessage) -> Self {
        Self {
            id: m.id,
            created_at: m.created_at,
            content: m.content,
            sender: m.sender,
            room_id: m.room,
        }
    }
}

/// GraphQL input for sending a message.
#[derive(InputObject)]
pub struct SendMessageInput {
    pub content: String,
    /// Public ID of the sender.
    pub sender: Uuid,
    /// Public ID of the room.
    pub room: Uuid,
    /// Client-generated idempotency key to prevent duplicate sends on retries.
    pub idempotency_key: Uuid,
}
