//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use chrono::Utc;
use sea_orm::{ActiveValue::Set, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "custom(\"enum_text\")", nullable)]
    pub status: Option<String>,
    pub room: Option<i32>,
    pub public_id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub last_seen_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::message::Entity")]
    Message,
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::Room",
        to = "super::room::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Room,
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    // Automatically set timestamps
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let current_time = Utc::now();
        // Always set updated_at
        self.updated_at = Set(current_time);

        // On insert, also set created_at
        if insert {
            self.created_at = Set(current_time);
            self.public_id = Set(Uuid::new_v4());
        }

        Ok(self)
    }
}
